apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 2  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo-app
          image: deploytokubernetes/echo-app :latest  # Replace with your Docker image
          ports:
            - containerPort: 5000  # The port the app is listening on
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  type: NodePort  # Exposes the service via NodePort
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80         # Internal port within the cluster
      targetPort: 5000 # Port on the container
      nodePort: 30080  # Exposed port on the node
